### ISSUE TITLE
Build docker image and host on ghcr

### ISSUE THREAD

**Issue by banesullivan** [marcoroth/dependabot-bump-together-action#4]
When using this action, the docker image is built from scratch because of 

https://github.com/marcoroth/dependabot-bump-together-action/blob/ab726ae3405ac60706b35fd8659da2ed009383b6/action.yml#L40

I believe this could be greatly improved for downstream projects by having CI in this repo build that docker image and host it in the container registry in this repo for the actions to pull

**Comment by banesullivan** [comment]
I suppose this would be incompatible with the options to choose the dependabot and bundler versions...

**Comment by marcoroth** [comment]
Hey @banesullivan, thanks for all the issues and PRs you submitted.

I think you are right and that's something that also annoyed me when I built this. This GitHub Action actually predates the GitHub Container Registry and thus is not using it because of that. 

I _think_ we can get rid of the dependabot and bundler versions. Let me check what we can do. I'm open to drop those options if needed.

**Comment by banesullivan** [comment]
thanks for looking into this! I'd really love to get this action working and production-ready - I have a huge need for it and I'm eager to help in any way

**Comment by marcoroth** [comment]
Resolved via #12.

Docker image is now available [here](https://github.com/marcoroth/dependabot-bump-together-action/pkgs/container/dependabot-bump-together-action) and directly used in action runs itself.
